name: 'tag'
env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches:
      - master
jobs:
  tag:
    runs-on: xcode
    steps:
      - uses: https://github.com/actions/checkout@v2
      - uses: https://github.com/christophebedard/tag-version-commit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
